# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-22 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginRegister', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('mdoel', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
