# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-22 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginRegister', '0002_companydetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydetails',
            old_name='mdoel',
            new_name='model',
        ),
    ]
