# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-22 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginRegister', '0003_auto_20180322_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
    ]
