# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-22 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginRegister', '0004_auto_20180322_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetails',
            name='quantity',
        ),
    ]
